sudo: required
dist: trusty
language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install xutils-dev doxygen libxcb-xkb-dev

compiler:
    - gcc
    - clang

script: ./autogen.sh && make && make check
